language: generic 
sudo:  required
services:
  - docker

before_install:
  - docker build -t deepakdehradun/multi-client ./myproj
  - docker build -t deepakdehradun/multi-ngnix ./ngnix
  - docker build -t deepakdehradun/multi-subscriber ./subscriber
  # log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push deepakdehradun/multi-client
  - docker push deepakdehradun/multi-ngnix
  - docker push deepakdehradun/multi-subscriber


deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-container
  env: MultiContainer-env
  bucket_name: elasticbeanstalk-us-east-1-755257926404
  bucket_path: multi-container
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY